### PR TITLE
Add stdio.h,stddef.h to storage.c

### PR DESCRIPTION
**Pull request by minkikim89**
A compilation error occurs.
My compiler is "Apple LLVM version 7.3.0 (clang-703.0.31)"
The error log is shown below.
```
storage.c:72:43: error: implicit declaration of function 'offsetof' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    memcpy((char *)io.buf+STORE_OFFSET, (char *)it+STORE_OFFSET, hdrtotal - STORE_OFFSET);
                                          ^
./storage.h:13:22: note: expanded from macro 'STORE_OFFSET'
#define STORE_OFFSET offsetof(item, nbytes)
                     ^
storage.c:72:43: error: unexpected type name 'item': expected expression
./storage.h:13:31: note: expanded from macro 'STORE_OFFSET'
#define STORE_OFFSET offsetof(item, nbytes)
                              ^
storage.c:72:43: error: use of undeclared identifier 'nbytes'
./storage.h:13:37: note: expanded from macro 'STORE_OFFSET'
#define STORE_OFFSET offsetof(item, nbytes)
                                    ^
storage.c:72:68: error: unexpected type name 'item': expected expression
                    memcpy((char *)io.buf+STORE_OFFSET, (char *)it+STORE_OFFSET, hdrtotal - STORE_OFFSET);
                                                                   ^
./storage.h:13:31: note: expanded from macro 'STORE_OFFSET'
#define STORE_OFFSET offsetof(item, nbytes)
...
```

if add stddef.h then...

```
storage.c:130:9: error: implicit declaration of function 'fprintf' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        fprintf(stderr, "Failed to allocate logger for storage compaction thread\n");
        ^
storage.c:130:9: error: declaration of built-in function 'fprintf' requires inclusion of the header <stdio.h> [-Werror,-Wbuiltin-requires-header]
storage.c:130:17: error: use of undeclared identifier 'stderr'
        fprintf(stderr, "Failed to allocate logger for storage compaction thread\n");
                ^
storage.c:228:17: error: use of undeclared identifier 'stderr'
        fprintf(stderr, "Can't create storage_write thread: %s\n",
                ^
storage.c:447:17: error: use of undeclared identifier 'stderr'
        fprintf(stderr, "Failed to allocate logger for storage compaction thread\n");
                ^
storage.c:453:17: error: use of undeclared identifier 'stderr'
        fprintf(stderr, "Failed to allocate readback buffer for storage compaction thread\n");
                ^
storage.c:561:17: error: use of undeclared identifier 'stderr'
        fprintf(stderr, "Can't create storage_compact thread: %s\n",
                ^
storage.c:587:17: error: use of undeclared identifier 'stderr'
        fprintf(stderr, "must supply size to ext_path, ie: ext_path=/f/e:64m (M|G|T|P supported)\n");
                ^
storage.c:629:21: error: use of undeclared identifier 'stderr'
            fprintf(stderr, "Unknown extstore bucket: %s\n", p);
                    ^
storage.c:639:17: error: use of undeclared identifier 'stderr'
        fprintf(stderr, "ext_path only presently supports the default bucket\n");
```

In short, storage.c should include stdio.h, stddef.h.

### CODE REVIEW

**Comment by dormando** [comment]
Thanks! Not sure if I'll ever have an OS X buildbot :(

**Comment by appsagg** [comment]
Have the same errors when try to compile on the CentOS 6.8

**Comment by dormando** [comment]
@appsagg I have a centos 7 but not a 6 builder. Odd that it would fail on 6 but not 7, have you changed the main packages at all from the defaults? (gcc version/etc)?

**Comment by appsagg** [comment]
cc1: warnings being treated as errors
storage.c: In function ‘storage_write’:
storage.c:70: error: implicit declaration of function ‘offsetof’
storage.c:70: error: expected expression before ‘item’
storage.c:70: error: expected expression before ‘item’
storage.c:70: error: expected expression before ‘item’
storage.c:82: error: expected expression before ‘item’
storage.c:82: error: expected expression before ‘item’
storage.c:82: error: expected expression before ‘item’
storage.c:86: error: expected expression before ‘item’
storage.c:86: error: expected expression before ‘item’
storage.c: In function ‘storage_write_thread’:
storage.c:128: error: implicit declaration of function ‘fprintf’
storage.c:128: error: incompatible implicit declaration of built-in function ‘fprintf’
storage.c:128: error: ‘stderr’ undeclared (first use in this function)
storage.c:128: error: (Each undeclared identifier is reported only once
storage.c:128: error: for each function it appears in.)
storage.c: In function ‘start_storage_write_thread’:
storage.c:226: error: incompatible implicit declaration of built-in function ‘fprintf’
storage.c:226: error: ‘stderr’ undeclared (first use in this function)
storage.c: In function ‘storage_compact_thread’:
storage.c:445: error: incompatible implicit declaration of built-in function ‘fprintf’
storage.c:445: error: ‘stderr’ undeclared (first use in this function)
storage.c:451: error: incompatible implicit declaration of built-in function ‘fprintf’
storage.c: In function ‘start_storage_compact_thread’:
storage.c:559: error: incompatible implicit declaration of built-in function ‘fprintf’
storage.c:559: error: ‘stderr’ undeclared (first use in this function)
storage.c: In function ‘storage_conf_parse’:
storage.c:585: error: incompatible implicit declaration of built-in function ‘fprintf’
storage.c:585: error: ‘stderr’ undeclared (first use in this function)
storage.c:627: error: incompatible implicit declaration of built-in function ‘fprintf’
storage.c:637: error: incompatible implicit declaration of built-in function ‘fprintf’

**Comment by appsagg** [comment]
> 
> 
> @appsagg I have a centos 7 but not a 6 builder. Odd that it would fail on 6 but not 7, have you changed the main packages at all from the defaults? (gcc version/etc)?
No, I have not change anything. Previous versions of memcached compiled successfully.

**Comment by martin-g** [comment]
> Thanks! Not sure if I'll ever have an OS X buildbot :(

@dormando: I can add MacOS to .travis.yml if you like: https://docs.travis-ci.com/user/reference/osx

**Comment by dormando** [comment]
@martin-g I thought the OS X ones cost money?

I wouldn't want one at any rate, I think. The travis instances are nice for a spot check but they overlap with the buildbots I have actual access to / control over. With yet another travis builder I'd fix maybe compile errors like this but anything deeper would end up just being noise.

**Comment by dormando** [comment]
out in 1.6.1!
